### ISSUE TITLE
Planejamento - Processo de Design de IHC

### ISSUE THREAD

**Issue by brenob6** [Interacao-Humano-Computador/2023.2-Ventoy#1]
## Descrição

Escolha do processo de design.

## Tarefas

- [x] O grupo deve escolher um processo de design.
- [x] Criar documento correspondente na sessão planejamento.

## Critérios de aceitação

O documento criado possui:

- [x] Ortografia correta?
- [x]  Histórico de versão?
- [x] Autor e revisor?
- [x] Parágrafo introdutório?
- [x] Tabelas e imagens com legenda e fonte?
- [x] As tabelas e imagens são chamadas no texto?
- [x] Referência bibliográficas?

**Comment by yabamiah** [comment]
Alguns pontos que vi até então no documento que precisam ser consertados:
- As imagens não estão aparecendo
- Erro de gramática na seção "Modelo Simples de Processo de Design", creio que deveria estar "Chamada" não "Chama", e logo em seguida deveria ser "o designer" no plural, e logo em seguida usar uma vírgula ao invés de ponto final .
- Na segunda figura esqueceram de escrever "Fonte"
- Em relação a escolhe do processo de design, seguiremos a risca ou de forma adaptada?
- E o markdown da legenda do histórico de versões não está marcado
