### ISSUE TITLE
Atas - Atas 02

### ISSUE THREAD

**Issue by brenob6** [Interacao-Humano-Computador/2023.2-Ventoy#2]
## Descrição

Documentação da segunda ata.

## Tarefas

- [x] Documentar ata da segunda reunião.

## Critérios de aceitação

O documento criado possui:

- [x] Ortografia correta?
- [x] Histórico de versão?
- [ ] Autor e revisor?
- [x] Parágrafo introdutório?
- [ ] Tabelas e imagens com legenda e fonte?
- [ ] As tabelas e imagens são chamados no texto?
- [x] Referência bibliográfica?

**Comment by yabamiah** [comment]
- Nem todas as legendas das tabelas estão centralizadas
- Criar tabela dos horários previstos
- Centralizar tabelas
- Falta as fontes das tabelas
- Falta colocar revisor
