### ISSUE TITLE
Verificação grupo 3

### ISSUE THREAD

**Issue by brenob6** [Interacao-Humano-Computador/2023.2-Ventoy#48]
## Artefatos a serem verificados

- [x]  Cronogramas
- [x]  Ferramentas
- [x]  HeatMap
- [x]  Metodologia
- [x]  Padronização do projeto
- [x]  Processos de Design
- [x]  Site Selecionado
- [x]  Sites Avaliados
- [x]  Aspectos Éticos
- [x]  Características da plataforma
- [x]  Cenários
- [x]  Árvore de Tarefas Concorrentes
- [x]  Guia de Estilo
- [x]  Análise Hierárquica de Tarefas
- [x]  Introspecção
- [x]  Metas de Usabilidade
- [x]  Observação
- [x]  Perfil de Usuário
- [x]  Personas
- [x]  Princípios Gerais do Projeto
 
## Analise de tarefas

- [x]  Planejamento da Avaliação da Análise de Tarefas
- [x]  Planejamento do Relato dos Resultados da Avaliação
- [x]  Relato dos Resultados
 
## Storyboard

- [x]  Planejamento da Avaliação do Storyboard
- [x]  Planejamento do Relato dos Resultados da avaliação do Storyboard
- [x]  Relato do Resultado - Storyboard
- [x]  Storyboards

## Protótipo de Papel

- [x]  Planejamento da Avaliação do Protótipo de Papel
- [x]  Planejamento do Relato dos Resultados da Avaliação do Protótipo de Papel

**Comment by Mayara-tech** [comment]
ficarei com a verificação do cronograma, das ferramentas, da instrospecção, do perfil de usuário e das personas.

**Comment by LimirioGuimaraes** [comment]
Ficarei responsável por todos os artefatos referentes aos storyboard's.

**Comment by MilenaBaruc** [comment]
Ficarei responsável com aspectos éticos, padronização do projeto, e os protótipos de papel

**Comment by LuisMiranda10** [comment]
Ficarei responsável por Heatmap, Metodologia, Sites Avaliados e Sites Selecionados

**Comment by yabamiah** [comment]
Ficarei responsável por Cenários, Princípios gerais do projeto, HTA e Planejamento da Avaliação da Análise de Tarefas

**Comment by brenob6** [comment]
Ficarei responsável por Processos de Design, Metas de Usabilidade, Planejamento do Relato dos Resultados da Avaliação e  Relato dos Resultados - Análise de Tarefas.

**Comment by arthurrochamoreira** [comment]
Fiquei responsável pelo Guia de Estilo, Observações, Caracteristicas Gerais e CTT
