### ISSUE TITLE
Verificação dos nossos artefatos

### ISSUE THREAD

**Issue by LimirioGuimaraes** [Interacao-Humano-Computador/2023.2-Ventoy#62]
## Planejamento
- [x] Cronograma
- [x] Ferramentas
- [x] Metodologia
- [x] Políticas
- [x] Heatmap
- [x] Processo design
- [x] Sites avaliados
- [x] Site escolhido
## Análise de Requisitos 
- [x] Aspectos Éticos
- [x] Perfil de Usuário
- [x] Persona
- [x] Cenários
### Elicitação
- [x] Entrevista
- [x] Brainstorming
- [x] Introspecção
- [x] Grupo de foco
### Análise de Tarefas
- [x] Análise Hierarquica de Tarefas - HTA
- [x] ConcurTaskTrees - CTT
## Análise de requisitos II
- [x] Princípios Gerais
- [ ] Características Gerais
- [x] Metas de Usabilidade
- [x] Guia de Estilo
### Storyboard
- [x] Planejamento da Avaliação do Storyboard
- [x] Planejamento do Relato dos Resultados
- [x] Relato dos Resultados do Storyboard
- [x] Storyboards
### Análise de Tarefas
- [x] Planejamento da Avaliação da Análise de Tarefas
- [x] Planejamento do Relato dos Resultados da Avaliação
- [x] Relato dos Resultados da Avaliação
### Protótipo de Papel
- [x] Planejamento da Avaliação do protótipo de papel
- [x] Planejamento do Relato dos resultados do protótipo de papel
- [x] Protótipos de papel
#### Relato dos Resultados protótipo de papel
- [x] Criar post no fórum
- [x] Acessar a aba de plugin
- [ ] Acessar a página de FAQ para consultar dúvida
- [x] Acessar a página de Testes de ISO para verificar os testes
- [ ] Realizar doação
- [x] Acessar a página de Compartilhamento de Experiências para consultar relatos
- [x] Iniciar o uso do Ventoy
### Protótipo de alta fidelidade
- [ ] Protótipos de alta fidelidade
- [x] Planejamento da Avaliação do protótipo de alta fidelidade
- [x] Planejamento do Relato dos resultados do protótipo de alta fidelidade
#### Relato dos Resultados protótipo de alta fidelidade
- [x] Criar post no fórum
- [x] Acessar a aba de plugin
- [x] Acessar a página de FAQ para consultar dúvida
- [ ] Acessar a página de Testes de ISO para verificar os testes
- [x] Realizar doação
- [x] Acessar a página de Compartilhamento de Experiências para consultar relatos
- [x] Iniciar o uso do Ventoy

**Comment by LimirioGuimaraes** [comment]
As verificações ficaram definidas para serem feitas em dupla ou trio, a dupla @Mayara-tech e @LimirioGuimaraes ficaram responsáveis pela verificação dos seguintes artefatos: Metodologia, Site escolhido, Cenários, Introspecção, Grupo de foco, Guia de Estilo, Planejamento da Avaliação do Storyboard, Planejamento do Relato dos Resultados, Planejamento do Relato dos Resultados da Avaliação, Planejamento da Avaliação do protótipo de papel, Criar post no fórum, Acessar a aba de plugin

**Comment by yabamiah** [comment]
O trio @LuisMiranda10 , @arthurrochamoreira  e @yabamiah ficaram responsáveis pela verificação dos seguintes artefatos: Ferramentas, Sites avaliados, Brainstorming, Análise Hierarquica de Tarefas - HTA, Metas de Usabilidade, Storyboards, Relato dos Resultados da Avaliação da Análise de tarefas, Protótipos de papel,  Acessar a página de Compartilhamento de Experiências para consultar relatos, Planejamento da Avaliação do protótipo de alta fidelidade, Princípios, Heatmap, Relato dos Resultados protótipo de alta fidelidade Iniciar o uso do Ventoy.

---
**Atualizado**

**Comment by brenob6** [comment]
Elicitação - entrevista
Relato dos resultados do prototipo de papel - Iniciar uso do Ventoy
Relato dos resultados do prototipo de alta fidelidade - Acessar a página de FAQ para consultar dúvida
Protótipos de alta fidelidade

**Comment by MilenaBaruc** [comment]
cronograma, políticas - planejamento
aspectos eticos - analise de requisitos
planejamento da avaliação - analise de tarefas
acessar a pagina de teste iso - prototipo de papel
planejamento do relato dos resultados, realizar doação - prototipo de alta fidelidade
