### ISSUE TITLE
Correção do artefatos

### ISSUE THREAD

**Issue by LimirioGuimaraes** [Interacao-Humano-Computador/2023.2-Ventoy#74]
## Planejamento
- [x] Cronograma
- [x] Ferramentas
- [x] Metodologia
- [x] Políticas
- [x] Heatmap
- [ ] Processo design
- [ ] Sites avaliados
- [x] Site escolhido
## Análise de Requisitos 
- [x] Aspectos Éticos
- [x] Perfil de Usuário
- [x] Persona
- [x] Cenários
### Elicitação
- [x] Entrevista
- [x] Brainstorming
- [x] Introspecção
- [ ] Grupo de foco
### Análise de Tarefas
- [x] Análise Hierarquica de Tarefas - HTA
- [x] ConcurTaskTrees - CTT
## Análise de requisitos II
- [x] Princípios Gerais
- [x] Características Gerais
- [x] Metas de Usabilidade
- [x] Guia de Estilo
### Storyboard
- [ ] Planejamento da Avaliação do Storyboard
- [x] Planejamento do Relato dos Resultados
- [ ] Relato dos Resultados do Storyboard
- [x] Storyboards
### Análise de Tarefas
- [x] Planejamento da Avaliação da Análise de Tarefas
- [ ] Planejamento do Relato dos Resultados da Avaliação
- [x] Relato dos Resultados da Avaliação
### Protótipo de Papel
- [ ] Planejamento da Avaliação do protótipo de papel
- [ ] Planejamento do Relato dos resultados do protótipo de papel
- [ ] Protótipos de papel
#### Relato dos Resultados protótipo de papel
- [x] Criar post no fórum
- [ ] Acessar a aba de plugin
- [x] Acessar a página de FAQ para consultar dúvida
- [ ] Acessar a página de Testes de ISO para verificar os testes
- [ ] Realizar doação
- [ ] Acessar a página de Compartilhamento de Experiências para consultar relatos
- [x] Iniciar o uso do Ventoy
### Protótipo de alta fidelidade
- [ ] Protótipos de alta fidelidade
- [x] Planejamento da Avaliação do protótipo de alta fidelidade
- [x] Planejamento do Relato dos resultados do protótipo de alta fidelidade
#### Relato dos Resultados protótipo de alta fidelidade
- [x] Criar post no fórum
- [ ] Acessar a aba de plugin
- [x] Acessar a página de FAQ para consultar dúvida
- [ ] Acessar a página de Testes de ISO para verificar os testes
- [ ] Realizar doação
- [ ] Acessar a página de Compartilhamento de Experiências para consultar relatos
- [x] Iniciar o uso do Ventoy

**Comment by LimirioGuimaraes** [comment]
Maquem quando terminaram de corrigir.

**Comment by yabamiah** [comment]
Terminei as correções :
Apresentações - vinicius X
site escolhido - vinicius X
instrospecção - vinicius X
HTA - vinicius X 
Principios gerais do projeto - vinicius  X
planejamento do relato storyboard - vinicius  X
relato dos resultados papel - vinicius X
planejamento do relato alta fidelidade - vinicius X
relato dos resultados alta fidelidade - vinicius X

**Comment by brenob6** [comment]
Finalizado:
Politicas
metodologia
cenarios
metas de usabilidade
storyboard
relato de papel
relato de alta fidelidade

**Comment by Mayara-tech** [comment]
Finalizado:
- Cronograma;
- perfil de usuario;
- persona;
- elicitação: entrevista
- planejamento da avaliação do hta
- relato de papel
- planejamento avaliacao prototipo alta fidelidade
- relato prototipo alta fidelidade
